name: Integration Tests

on:
  push:
    paths-ignore:
      - 'docs/**'
      - '**/*.md'
    branches:
      - master
  pull_request:
  schedule:
    - cron: "0 1 * * *"

env:
  redis_stack_version: 6.2.2-v5

jobs:
  build_and_test_ubuntu:
    name: Build and Test on Ubuntu
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: .NET Core 6
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '6.0.x'
      - name: .NET Core 7
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '7.0.x'
      - name: run redis-stack-server docker
        run: docker run -p 6379:6379 -d redis/redis-stack-server:edge
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore /p:ContinuousIntegrationBuild=true
      - name: Test
        run: dotnet test -f net6.0 --no-build --verbosity normal /p:CollectCoverage=true /p:CoverletOutputFormat=opencover
      - name: Test
        run: dotnet test -f net7.0 --no-build --verbosity normal /p:CollectCoverage=true /p:CoverletOutputFormat=opencover
      - name: Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{secrets.CODECOV_TOKEN}}
          verbose: true
      - name: Build
        run: dotnet pack -c Release

  build_and_test_windows:
    name: Build and Test on Windows
    runs-on: windows-latest
    steps:
      - name: Download redis-stack
        run: Invoke-WebRequest https://github.com/ianwalter/redis-stack/releases/latest/download/redis-stack.zip -OutFile redis-stack.zip
      - name: Extract redis-stack
        run: Expand-Archive redis-stack.zip -DestinationPath .\redis-stack\
      - name: Start redis-stack
        run: .\redis-stack\redis-stack.exe start
      - name: Wait for redis-stack to start
        run: Start-Sleep -s 5
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore /p:ContinuousIntegrationBuild=true
      - name: Test
        run: dotnet test -f net481 --no-build --verbosity normal